services:
  postgresql:
    container_name: temporal-postgresql
    environment:
      POSTGRES_PASSWORD: temporal
      POSTGRES_USER: temporal
    image: postgres:13
    networks:
      - demo-network
    ports:
      - 5432:5432
  temporal:
    depends_on:
      - postgresql
    environment:
      - DB=postgres12
      - DB_PORT=5432
      - POSTGRES_USER=temporal
      - POSTGRES_PWD=temporal
      - POSTGRES_SEEDS=postgresql
    image: temporalio/auto-setup:1.25.0
    networks:
      - demo-network
    ports:
      - 7233:7233
      - 7243:7243
    volumes:
      - ./dynamicconfig:/etc/temporal/config/dynamicconfig
  ui:
    image: temporalio/ui:2.30.2
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_CORS_ORIGINS=http://localhost:3000
      - TEMPORAL_UI_PORT=8233
    networks:
      - demo-network
    ports:
      - 8233:8233
networks:
  demo-network:
    driver: bridge
    name: demo-network
