name: Docker

on:
  push:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2.4.1

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push core worker Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./game
          file: ./game/Dockerfile.core-worker
          platforms: linux/amd64,linux/arm64
          tags: ${{ env.REGISTRY }}/temporalio/snakes-core-worker:latest
          push: true
          cache-from: type=registry,ref=${{ env.REGISTRY }}/temporalio/snakes-core-worker-buildcache:latest
          cache-to: type=registry,ref=${{ env.REGISTRY }}/temporalio/snakes-core-worker-buildcache:latest,mode=max
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push snake worker Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./game/go
          file: ./game/Dockerfile.snake-worker
          platforms: linux/amd64,linux/arm64
          tags: ${{ env.REGISTRY }}/temporalio/snakes-worker:latest
          push: true
          cache-from: type=registry,ref=${{ env.REGISTRY }}/temporalio/snakes-worker-buildcache:latest
          cache-to: type=registry,ref=${{ env.REGISTRY }}/temporalio/snakes-worker-buildcache:latest,mode=max
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push UI Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./snakes
          platforms: linux/amd64,linux/arm64
          tags: ${{ env.REGISTRY }}/temporalio/snakes-ui:latest
          push: true
          cache-from: type=registry,ref=${{ env.REGISTRY }}/temporalio/snakes-ui-buildcache:latest
          cache-to: type=registry,ref=${{ env.REGISTRY }}/temporalio/snakes-ui-buildcache:latest,mode=max
          github-token: ${{ secrets.GITHUB_TOKEN }}
